name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]    

    steps:
    - uses: actions/checkout@v2
    - name: make
      run: make
    - name: bench
      run: ./bench
    - name: words
      run: ./words benchs/words.txt
    - name: hashmap_1
      run: ./hashmap 1048576
    - name: hashmap_2
      run: ./hashmap 2097152
    - name: hashmap_3
      run: ./hashmap 4194304
    - name: hashmap_4
      run: ./hashmap 8388608

