name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v2
    - name: make
      run: make all
    - name: bench
      run: time ./bench
    - name: words
      run: time ./words benchs/words.txt
    - name: robin_hood_1
      run: time ./robin_hood 1000000
    - name: robin_hood_2
      run: time ./robin_hood 2000000
    - name: robin_hood_3
      run: time ./robin_hood 4000000
    - name: robin_hood_4
      run: time ./robin_hood 8000000
    - name: robin_hood_5
      run: time ./robin_hood 16000000

