name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]    

    steps:
    - uses: actions/checkout@v2
    - name: make
      run: make all
    - name: bench
      run: time ./bench
    - name: words
      run: time ./words benchs/words.txt
    - name: robin_hood_1
      run: time ./robin_hood 1048576
    - name: hashmap_2
      run: time ./robin_hood 2097152
    - name: hashmap_3
      run: time ./robin_hood 4194304
    - name: hashmap_4
      run: time ./robin_hood 8388608

